[env]

WIFI_SSID = "xxx"
WIFI_PASSWORD = "xxx"

# GET WITH `ipconfig getifaddr en0`
TOBOGGAN_HOST = "192.168.1.137"
TOBOGGAN_PORT = 8080

[tools]
"cargo:ldproxy" = "latest"
"cargo:espflash" = "latest"
"cargo:espup" = "latest"
"cargo:esp-generate" = "latest"

[tasks.check]
description = "Check the code compiles"
run = "cargo check"

[tasks.lint]
description = "Run clippy linter"
run = "cargo clippy"

[tasks.fix]
description = "Fix formatting and lint issues"
run = """
cargo +nightly fmt
cargo clippy --fix --allow-dirty --allow-staged
"""

[tasks.fmt]
description = "Format code with rustfmt"
run = "cargo +nightly fmt"

[tasks.flash]
description = "Flash the device"
run = "espflash flash target/xtensa-esp32s3-espidf/release/toboggan-esp32"

[tasks.ip]
description = "Return the host IP"
run = "ipconfig getifaddr en0"
