[env]

WIFI_SSID = "xxx"
WIFI_PASSWORD = "xxx"

# GET WITH `ipconfig getifaddr en0`
TOBOGGAN_HOST = "192.168.1.137"
TOBOGGAN_PORT = 8080

[tools]
"cargo:ldproxy" = "latest"
"cargo:espflash" = "latest"
"cargo:espup" = "latest"
"cargo:esp-generate" = "latest"

[tasks.flash]
description = "Flash the device"
run = "espflash flash --monitor target/xtensa-esp32s3-espidf/release/toboggan-esp32"

[tasks.ip]
description = "Return the host IP"
run = "ipconfig getifaddr en0"
